project:
  type: manuscript
  output-dir: docs

format-links: false

notebook-links: false

execute:
  freeze: auto
  debug: true

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  agu-pdf: default



